"""Add ontology table and link to documents

Revision ID: 1b8a7b3e9c2d
Revises: 4a9d7c6e3b2f
Create Date: 2025-11-21 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b8a7b3e9c2d'
down_revision = '4a9d7c6e3b2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ontologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schema_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ontologies_id'), 'ontologies', ['id'], unique=False)
    
    op.add_column('documents', sa.Column('ontology_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'ontologies', ['ontology_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'ontology_id')
    
    op.drop_index(op.f('ix_ontologies_id'), table_name='ontologies')
    op.drop_table('ontologies')
    # ### end Alembic commands ###
