"""Rebuild symbolic foundation with DomainConfig and Canonical Store

Revision ID: 2c7a8d5b4e3f
Revises: 1b8a7b3e9c2d
Create Date: 2025-11-21 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision = '2c7a8d5b4e3f'
down_revision = '1b8a7b3e9c2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Create new tables for the canonical store
    op.create_table('domain_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schema_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_domain_configs_id'), 'domain_configs', ['id'], unique=False)

    op.create_table('canonical_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.VECTOR(dimensions=1536), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_canonical_nodes_id'), 'canonical_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_canonical_nodes_node_type'), 'canonical_nodes', ['node_type'], unique=False)

    op.create_table('node_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('canonical_node_id', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_node_id'], ['canonical_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_index(op.f('ix_node_aliases_alias'), 'node_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_node_aliases_id'), 'node_aliases', ['id'], unique=False)

    # Drop old ontology table and foreign key from documents
    op.drop_constraint('documents_ontology_id_fkey', 'documents', type_='foreignkey')
    op.drop_column('documents', 'ontology_id')
    op.drop_table('ontologies')

    # Add new foreign key to documents
    op.add_column('documents', sa.Column('domain_config_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_documents_domain_config', 'documents', 'domain_configs', ['domain_config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_domain_config', 'documents', type_='foreignkey')
    op.drop_column('documents', 'domain_config_id')

    # Recreate old ontology table and column
    op.create_table('ontologies',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('schema_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='ontologies_pkey'),
        sa.UniqueConstraint('name', name='ontologies_name_key')
    )
    op.add_column('documents', sa.Column('ontology_id', sa.Integer(), nullable=True))
    op.create_foreign_key('documents_ontology_id_fkey', 'documents', 'ontologies', ['ontology_id'], ['id'])

    # Drop new tables
    op.drop_index(op.f('ix_node_aliases_id'), table_name='node_aliases')
    op.drop_index(op.f('ix_node_aliases_alias'), table_name='node_aliases')
    op.drop_table('node_aliases')
    op.drop_index(op.f('ix_canonical_nodes_node_type'), table_name='canonical_nodes')
    op.drop_index(op.f('ix_canonical_nodes_id'), table_name='canonical_nodes')
    op.drop_table('canonical_nodes')
    op.drop_index(op.f('ix_domain_configs_id'), table_name='domain_configs')
    op.drop_table('domain_configs')

    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
