"""Add enrichment queue table

Revision ID: 3a2b1c0d9e8f
Revises: 2c7a8d5b4e3f
Create Date: 2025-11-21 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2b1c0d9e8f'
down_revision = '2c7a8d5b4e3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichment_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('context_chunk', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='enrichmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_queue_id'), 'enrichment_queue', ['id'], unique=False)
    op.create_index(op.f('ix_enrichment_queue_name'), 'enrichment_queue', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrichment_queue_name'), table_name='enrichment_queue')
    op.drop_index(op.f('ix_enrichment_queue_id'), table_name='enrichment_queue')
    op.drop_table('enrichment_queue')
    # ### end Alembic commands ###
