"""Initial PostgreSQL schema with pgvector

Revision ID: 4cc72cd32f0f
Revises:
Create Date: 2025-09-30 12:19:14.228257

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4cc72cd32f0f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "async_tasks",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("task_name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "SUCCESS", "FAILED", "CANCELLED", name="taskstatus"),
            nullable=False,
        ),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_task_created", "async_tasks", ["created_at"], unique=False)
    op.create_index("idx_task_status", "async_tasks", ["status"], unique=False)
    op.create_index(op.f("ix_async_tasks_task_name"), "async_tasks", ["task_name"], unique=False)
    op.create_table(
        "canonical_entities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_id", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("entity_type", sa.Enum("COMPANY", "SCHOOL", name="entitytype"), nullable=False),
        sa.Column("entity_metadata", sa.JSON(), nullable=True),
        sa.Column("embedding", Vector(1536), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_canonical_entities_canonical_id"),
        "canonical_entities",
        ["canonical_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_canonical_entities_entity_type"),
        "canonical_entities",
        ["entity_type"],
        unique=False,
    )
    op.create_table(
        "enrichment_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_id", sa.String(length=255), nullable=False),
        sa.Column("entity_type", sa.Enum("COMPANY", "SCHOOL", name="entitytype"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "NEEDS_REVIEW",
                name="enrichmentstatus",
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_enrichment_status", "enrichment_queue", ["status"], unique=False)
    op.create_index(
        op.f("ix_enrichment_queue_canonical_id"), "enrichment_queue", ["canonical_id"], unique=True
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("embedding", Vector(1536), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skills_canonical_name"), "skills", ["canonical_name"], unique=True)
    op.create_table(
        "aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alias_name", sa.String(length=255), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_aliases_skill_id", "aliases", ["skill_id"], unique=False)
    op.create_index(op.f("ix_aliases_alias_name"), "aliases", ["alias_name"], unique=True)
    op.create_table(
        "entity_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alias_name", sa.String(length=255), nullable=False),
        sa.Column("canonical_id", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["canonical_id"], ["canonical_entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_entity_aliases_canonical_id", "entity_aliases", ["canonical_id"], unique=False
    )
    op.create_index(
        op.f("ix_entity_aliases_alias_name"), "entity_aliases", ["alias_name"], unique=True
    )
    op.create_table(
        "hierarchy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["child_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("child_id", "parent_id", name="uq_hierarchy"),
    )
    op.create_index("idx_hierarchy_child", "hierarchy", ["child_id"], unique=False)
    op.create_index("idx_hierarchy_parent", "hierarchy", ["parent_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_hierarchy_parent", table_name="hierarchy")
    op.drop_index("idx_hierarchy_child", table_name="hierarchy")
    op.drop_table("hierarchy")
    op.drop_index(op.f("ix_entity_aliases_alias_name"), table_name="entity_aliases")
    op.drop_index("idx_entity_aliases_canonical_id", table_name="entity_aliases")
    op.drop_table("entity_aliases")
    op.drop_index(op.f("ix_aliases_alias_name"), table_name="aliases")
    op.drop_index("idx_aliases_skill_id", table_name="aliases")
    op.drop_table("aliases")
    op.drop_index(op.f("ix_skills_canonical_name"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(op.f("ix_enrichment_queue_canonical_id"), table_name="enrichment_queue")
    op.drop_index("idx_enrichment_status", table_name="enrichment_queue")
    op.drop_table("enrichment_queue")
    op.drop_index(op.f("ix_canonical_entities_entity_type"), table_name="canonical_entities")
    op.drop_index(op.f("ix_canonical_entities_canonical_id"), table_name="canonical_entities")
    op.drop_table("canonical_entities")
    op.drop_index(op.f("ix_async_tasks_task_name"), table_name="async_tasks")
    op.drop_index("idx_task_status", table_name="async_tasks")
    op.drop_index("idx_task_created", table_name="async_tasks")
    op.drop_table("async_tasks")
    # ### end Alembic commands ###
